Use 4.8.0 version
jboss-fuse/camel-spring-boot-examples pull request #164
Opened 2024-11-07 07:51 UTC by Croway

2024-11-07 09:37 UTC, cunningt requested changes
https://github.com/Croway/camel-spring-boot-examples/blob/camel-spring-boot-examples-4.8.0-branch/servicecall/services/pom.xml

Can you do a mvn clean install build to double check?

2024-11-07 12:26 UTC, Croway commented
I am truly sorry, I noticed that this morning, but didn't push the fix, it is done now

2024-11-20 15:36 UTC, mcarlett approved these changes

2024-11-20 16:01 UTC, cunningt approved these changes

2024-11-20 16:02 UTC, merged